### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by pint1022** [hughperkins/coriander#65]
Hi,
I followed the instruction to build the coriander on centos 7.0 running python3.6. gcc is version 4.9.2. It fails to build with the command ' python install_distro.py'. Here is the output from the script:
make[2]: *** [CMakeFiles/patch_hostside.dir/third_party/argparsecpp/argparsecpp.cpp.o] Error 1
make[2]: *** [CMakeFiles/patch_hostside.dir/src/mutations.cpp.o] Error 1
cc1plus: error: -Werror=date-time: no option -Wdate-time
cc1plus: error: -Werror=date-time: no option -Wdate-time
make[2]: *** [CMakeFiles/patch_hostside.dir/src/patch_hostside.cpp.o] Error 1
cc1plus: error: -Werror=date-time: no option -Wdate-time
make[2]: *** [CMakeFiles/patch_hostside.dir/src/GlobalNames.cpp.o] Error 1
make[2]: *** [CMakeFiles/patch_hostside.dir/src/struct_clone.cpp.o] Error 1
make[2]: *** [CMakeFiles/patch_hostside.dir/src/readIR.cpp.o] Error 1
make[1]: *** [CMakeFiles/patch_hostside.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  9%] Building CXX object CMakeFiles/easycl.dir/src/EasyCL/CLWrapper.cpp.o
[ 11%] Building CXX object CMakeFiles/easycl.dir/src/EasyCL/CLKernel.cpp.o
[ 11%] Building CXX object CMakeFiles/easycl.dir/src/EasyCL/deviceinfo_helper.cpp.o
[ 15%] Building CXX object CMakeFiles/easycl.dir/src/EasyCL/DeviceInfo.cpp.o
[ 17%] Building CXX object CMakeFiles/easycl.dir/src/EasyCL/util/easycl_stringhelper.cpp.o
[ 17%] Building CXX object CMakeFiles/easycl.dir/src/EasyCL/EasyCL.cpp.o
[ 17%] Building CXX object CMakeFiles/easycl.dir/src/EasyCL/DevicesInfo.cpp.o
[ 19%] Building CXX object CMakeFiles/easycl.dir/src/EasyCL/platforminfo_helper.cpp.o
[ 21%] Linking CXX shared library libeasycl.so
[ 21%] Built target easycl
make: *** [all] Error 2
p.returncode 2
Traceback (most recent call last):
  File "install_distro.py", line 222, in <module>
    main(**args.__dict__)
  File "install_distro.py", line 207, in main
    install_coriander(install_dir=install_dir)
  File "install_distro.py", line 175, in install_coriander
    run(['make', '-j', '8'])
  File "install_distro.py", line 88, in run
    assert p.returncode == 0
AssertionError

Where -Werror is defined? 
what might be the problem?

thanks,
steven

**Comment by pint1022** [comment]
The build script works fine on ubuntu.
